import { notFound, redirect } from "next/navigation";
import { Banknote, Building2, CalendarClock, CircleDollarSign, Clock3, MapPin, ReceiptText, Star, UserRoundCheck, Users } from "lucide-react";
import { BusinessAdminAssignment } from "@/components/business-admin-assignment";
import { db } from "@/lib/db";
import { getAdminSession } from "@/lib/server/admin-session";
import { formatMoney } from "@/lib/utils";

export const dynamic = "force-dynamic";

const labels: Record<string, string> = { AWAITING_DEPOSIT: "Chờ đối soát cọc", DEPOSIT_CONFIRMED: "Đã nhận cọc · cần phân công", READY: "Sẵn sàng triển khai", IN_SERVICE: "Đang phục vụ", AWAITING_BALANCE: "Chờ thanh toán phần còn lại", COMPLETED: "Đã hoàn tất", CANCELLED: "Đã hủy" };

export default async function AdminBusinessDetailPage({ params }: { params: Promise<{ eventCode: string }> }) {
  const session = await getAdminSession();
  if (!session || !["OWNER", "BRANCH_MANAGER"].includes(session.role)) redirect("/admin");
  const { eventCode } = await params;
  const event = await db.officeEvent.findUnique({ where: { eventCode }, include: { branch: true, customer: true, leadTherapist: true, payments: { orderBy: { createdAt: "asc" } }, ledgerEntries: { orderBy: { occurredAt: "asc" } }, tipPayout: true } });
  if (!event) notFound();
  if (session.role !== "OWNER" && session.branchId !== event.branchId) redirect("/admin/office-events");
  const therapists = await db.therapist.findMany({ where: { branchId: event.branchId, status: "ACTIVE" }, orderBy: [{ ratingAvg: "desc" }, { fullName: "asc" }] });
  const elapsed = event.actualStartedAt && event.actualEndedAt ? Math.max(0, Math.round((event.actualEndedAt.getTime() - event.actualStartedAt.getTime()) / 60_000)) : null;
  const variance = event.actualStartedAt ? Math.round((event.actualStartedAt.getTime() - event.startsAt.getTime()) / 60_000) : null;
  const received = event.payments.filter((payment) => payment.status === "CONFIRMED" && payment.direction === "IN").reduce((sum, payment) => sum + (payment.receivedAmount ?? payment.amount), 0);
  const due = Math.max(0, event.totalAmount - Math.min(event.paidAmount, event.totalAmount));
  return <div className="mx-auto max-w-6xl px-4 py-6 sm:px-6"><header className="relative overflow-hidden rounded-[2rem] bg-gradient-to-br from-[#241614] via-[#5b2d1e] to-[#9b1f24] p-6 text-white shadow-2xl"><div className="absolute -right-12 -top-12 h-36 w-36 rounded-full bg-[#f6dd93]/20 blur-2xl"/><p className="relative text-xs font-bold uppercase tracking-[0.16em] text-[#f6dd93]">Trung tâm vận hành Tâm An Business</p><div className="relative mt-2 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-semibold">{event.companyName}</h1><p className="mt-1 text-sm text-white/70">{event.eventCode} · {event.branch.name}</p></div><span className="rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-xs font-semibold">{labels[event.status] ?? event.status}</span></div></header>
  <div className="mt-4 grid grid-cols-2 gap-2.5 md:grid-cols-4"><Metric icon={<CircleDollarSign/>} label="Tổng Bill" value={formatMoney(event.totalAmount)}/><Metric icon={<Banknote/>} label="Thực nhận" value={formatMoney(received)}/><Metric icon={<ReceiptText/>} label="Công nợ còn lại" value={formatMoney(due)} warn={due > 0}/><Metric icon={<Clock3/>} label="Phục vụ thực tế" value={elapsed === null ? "Chưa chốt" : `${elapsed} phút`}/></div>
  <div className="mt-4 grid gap-4 lg:grid-cols-[1.1fr_0.9fr]"><section className="rounded-[2rem] border border-[#e7d6ca] bg-white p-5 shadow-lg"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#c64b32]">Dữ liệu triển khai</p><h2 className="mt-1 text-xl font-semibold">Ai · ở đâu · khi nào</h2><div className="mt-4 grid grid-cols-2 gap-2.5"><Info icon={<Building2/>} label="Doanh nghiệp" value={event.companyName}/><Info icon={<UserRoundCheck/>} label="Người đặt" value={`${event.contactName ?? event.customer?.fullName ?? "—"} · ${event.contactPhone ?? event.customer?.phone ?? "—"}`}/><Info icon={<MapPin/>} label="Địa điểm thực tế" value={event.location} wide/><Info icon={<CalendarClock/>} label="Kế hoạch" value={event.startsAt.toLocaleString("vi-VN", { dateStyle: "short", timeStyle: "short", timeZone: "Asia/Ho_Chi_Minh" })}/><Info icon={<Clock3/>} label="Sai lệch bắt đầu" value={variance === null ? "Chưa bắt đầu" : variance === 0 ? "Đúng giờ" : `${variance > 0 ? "+" : ""}${variance} phút`}/><Info icon={<Users/>} label="Năng lực triển khai" value={`${event.headcount} người · ${event.requiredTherapists} KTV · ${event.durationMin} phút/người`} wide/>{event.customerRating ? <Info icon={<Star/>} label="Đánh giá khách hàng" value={`${event.customerRating}/5 · ${event.customerComment ?? "Không có ghi chú"}`} wide/> : null}</div></section><BusinessAdminAssignment eventCode={event.eventCode} initialTherapistId={event.leadTherapistId} therapists={therapists.map((therapist) => ({ id: therapist.id, label: `${therapist.fullName} · ${therapist.ratingAvg.toFixed(1)}★ · ${therapist.servedCount} lượt` }))}/></div>
  <section className="mt-4 rounded-[2rem] border border-[#e7d6ca] bg-white p-5 shadow-lg"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#c64b32]">Dòng tiền có đối soát</p><h2 className="mt-1 text-xl font-semibold">Giao dịch & hạch toán</h2></div><CircleDollarSign className="text-[#c64b32]"/></div><div className="mt-4 space-y-2">{event.payments.map((payment) => <div key={payment.id} className="grid grid-cols-[1fr_auto] items-center gap-3 rounded-2xl bg-[#fdf8f3] p-3"><div><p className="text-sm font-semibold">{payment.type === "DEPOSIT" ? "Đặt cọc Business" : payment.type === "SERVICE_PAYMENT" ? "Thanh toán phần còn lại" : "Tip KTV ngoài Bill"}</p><p className="mt-1 text-[11px] text-[#826f66]">{payment.status === "CONFIRMED" ? `Đã đối soát ${payment.paidAt?.toLocaleString("vi-VN", { timeZone: "Asia/Ho_Chi_Minh" }) ?? ""}` : "Đang chờ ngân hàng"}</p></div><p className={`text-sm font-bold ${payment.status === "CONFIRMED" ? "text-[#17744b]" : "text-[#c64b32]"}`}>{formatMoney(payment.receivedAmount ?? payment.amount)}</p></div>)}{event.payments.length === 0 ? <p className="rounded-2xl border border-dashed border-[#e7d6ca] p-5 text-center text-sm text-[#76665d]">Chưa phát sinh giao dịch.</p> : null}</div>{event.tipPayout ? <div className="mt-3 rounded-2xl bg-[#effaf4] p-3 text-xs text-[#17744b]">Tip KTV trưởng {formatMoney(event.tipPayout.amount)} · {event.tipPayout.status === "PAID" ? "đã chi" : "chờ chi cuối ngày"}.</div> : null}</section></div>;
}
function Metric({ icon, label, value, warn }: { icon: React.ReactNode; label: string; value: string; warn?: boolean }) { return <div className="rounded-3xl border border-[#e7d6ca] bg-white p-4 text-center shadow-sm"><span className="mx-auto flex w-fit text-[#c64b32] [&>svg]:h-5 [&>svg]:w-5">{icon}</span><p className="mt-2 text-[10px] uppercase tracking-wide text-[#826f66]">{label}</p><p className={`mt-1 text-base font-bold ${warn ? "text-[#c64b32]" : ""}`}>{value}</p></div>; }
function Info({ icon, label, value, wide }: { icon: React.ReactNode; label: string; value: string; wide?: boolean }) { return <div className={`${wide ? "col-span-2" : ""} rounded-2xl bg-[#fdf8f3] p-3`}><p className="flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-wide text-[#c64b32] [&>svg]:h-4 [&>svg]:w-4">{icon}{label}</p><p className="mt-1 text-xs font-semibold leading-5">{value}</p></div>; }
