export type XgroupRole = "XGROUP_SUPER_ADMIN" | "DISTRICT_SALES_MANAGER";
export type XgroupSection = "overview" | "finance" | "districts" | "affiliates" | "assets" | "reconciliation";

export type XgroupDashboardData = {
  generatedAt: string;
  reportingMode: "UAT_WITH_DEMO" | "PRODUCTION_LIVE_ONLY";
  scope: {
    role: XgroupRole;
    districtId: string | null;
    districtLabel: string;
    canManageAllDistricts: boolean;
    canApprovePayouts: boolean;
  };
  range: { from: string; to: string; label: string; targetGmv: number };
  finance: {
    bookedGmv: number;
    recognizedGmv: number;
    collected: number;
    receivable: number;
    depositCollected: number;
    tipExcluded: number;
    annualTarget: number;
    targetProgress: number;
    eventCount: number;
    completedCount: number;
    activeCompanyCount: number;
    allocation: {
      grossAmount: number;
      deliveryTeamAmount: number;
      platformAndDistributionAmount: number;
      ktvDirect: number;
      teamLeader: number;
      xgroupPlatform: number;
      districtDirector: number;
      directAffiliate: number;
    };
  };
  quality: {
    attributionCoveragePercent: number;
    attributedEventCount: number;
    unassignedEventCount: number;
    unassignedGmv: number;
    pendingComplianceCount: number;
    overdueAllocationCount: number;
  };
  series: Array<{ key: string; label: string; gmv: number; collected: number; xgroup: number }>;
  districts: Array<{
    id: string;
    code: string;
    name: string;
    city: string;
    managerName: string;
    annualTarget: number;
    gmv: number;
    collected: number;
    progress: number;
    eventCount: number;
    companyCount: number;
    activeAffiliateCount: number;
    leadCount: number;
    conversionRate: number;
  }>;
  affiliates: Array<{
    id: string;
    code: string;
    displayName: string;
    organization: string | null;
    title: string | null;
    phone: string | null;
    email: string | null;
    profile: string;
    districtId: string;
    districtName: string;
    status: string;
    commissionRateBps: number;
    conflictDisclosureRequired: boolean;
    conflictDisclosureAccepted: boolean;
    complianceNote: string | null;
    clickCount: number;
    leadCount: number;
    completedCount: number;
    conversionRate: number;
    gmv: number;
    commission: number;
    assetCount: number;
  }>;
  assets: Array<{
    id: string;
    code: string;
    type: "LINK" | "QR" | "VIDEO";
    title: string;
    status: string;
    districtId: string | null;
    districtName: string;
    affiliateId: string | null;
    affiliateName: string;
    destinationPath: string;
    videoUrl: string | null;
    trackingPath: string;
    clickCount: number;
    leadCount: number;
    completedCount: number;
    conversionRate: number;
    gmv: number;
  }>;
  leads: Array<{
    id: string;
    leadCode: string;
    companyName: string;
    contactName: string | null;
    contactPhone: string | null;
    officeAddress: string | null;
    districtId: string | null;
    districtName: string;
    affiliateName: string;
    sourceLabel: string;
    stage: string;
    estimatedGmv: number;
    nextActionAt: string | null;
    nextAction: string | null;
    createdAt: string;
  }>;
  events: Array<{
    id: string;
    eventCode: string;
    companyName: string;
    location: string;
    startsAt: string;
    status: string;
    districtName: string;
    affiliateName: string;
    sourceLabel: string;
    gmv: number;
    paidAmount: number;
    receivable: number;
    allocations: Array<{
      id: string;
      recipient: string;
      label: string;
      amount: number;
      rateBps: number;
      beneficiaryLabel: string;
      status: string;
      dueAt: string | null;
      paidAt: string | null;
      bankReference: string | null;
    }>;
  }>;
  managers: Array<{ id: string; name: string; username: string | null; districtId: string | null }>;
};

