import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { Building2, CalendarClock, CircleDollarSign, Clock3, MapPin, ReceiptText, ShieldCheck, UserRoundCheck, Users } from "lucide-react";
import { BusinessReviewForm } from "@/components/business-review-form";
import { db } from "@/lib/db";
import { canAccessBusinessEvent } from "@/lib/server/business-access";
import { formatMoney } from "@/lib/utils";

export const dynamic = "force-dynamic";

const labels: Record<string, string> = { AWAITING_DEPOSIT: "Chờ đối soát cọc", DEPOSIT_CONFIRMED: "Đã nhận cọc · đang điều phối", READY: "Sẵn sàng triển khai", IN_SERVICE: "Đang phục vụ", AWAITING_BALANCE: "Chờ thanh toán phần còn lại", COMPLETED: "Đã hoàn tất dịch vụ & thanh toán", CANCELLED: "Đã hủy" };

export default async function BusinessDetailPage({ params }: { params: Promise<{ eventCode: string }> }) {
  const { eventCode } = await params;
  const event = await db.officeEvent.findUnique({ where: { eventCode }, include: { branch: true, leadTherapist: true, payments: { orderBy: { createdAt: "asc" } }, tipPayout: true } });
  if (!event) notFound();
  const access = await canAccessBusinessEvent(event);
  if (!access.allowed) redirect(`/doanh-nghiep?business=${encodeURIComponent(eventCode)}`);
  const elapsedMinutes = event.actualStartedAt && event.actualEndedAt ? Math.max(0, Math.round((event.actualEndedAt.getTime() - event.actualStartedAt.getTime()) / 60_000)) : null;
  const due = Math.max(0, event.totalAmount - Math.min(event.paidAmount, event.totalAmount));
  const depositConfirmed = event.payments.find((payment) => payment.type === "DEPOSIT" && payment.status === "CONFIRMED");
  const balanceConfirmed = event.payments.find((payment) => payment.type === "SERVICE_PAYMENT" && payment.status === "CONFIRMED");
  return <main className="min-h-screen bg-[radial-gradient(circle_at_top,#ead2ac_0,#fdf8f3_38%,#f4ece6_100%)] px-4 py-6 text-[#211817]"><div className="mx-auto max-w-3xl space-y-4"><header className="relative overflow-hidden rounded-[2rem] bg-gradient-to-br from-[#241614] via-[#5b2d1e] to-[#9b1f24] p-6 text-white shadow-2xl"><div className="absolute -right-10 -top-10 h-32 w-32 rounded-full bg-[#f6dd93]/20 blur-2xl"/><p className="relative flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-[0.16em] text-[#f6dd93]"><ShieldCheck size={14}/> Hồ sơ vận hành đã xác thực</p><h1 className="relative mt-3 text-2xl font-semibold">{event.companyName}</h1><p className="relative mt-1 text-sm text-white/70">{event.eventCode}</p><span className="relative mt-4 inline-flex rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-xs font-semibold">{labels[event.status] ?? event.status}</span></header>
  <section className="grid grid-cols-2 gap-2.5 rounded-[2rem] border border-[#e7d6ca] bg-white p-4 shadow-lg sm:grid-cols-4"><Metric icon={<Building2 size={16}/>} label="Cơ sở phụ trách" value={event.branch.name.replace("Tâm An Center · ", "")}/><Metric icon={<UserRoundCheck size={16}/>} label="KTV trưởng" value={event.leadTherapist?.fullName ?? "Đang phân công"}/><Metric icon={<Users size={16}/>} label="Quy mô" value={`${event.headcount} người · ${event.requiredTherapists} KTV`}/><Metric icon={<Clock3 size={16}/>} label="Thời lượng thực tế" value={elapsedMinutes === null ? "Chưa chốt giờ" : `${elapsedMinutes} phút`}/><Metric icon={<MapPin size={16}/>} label="Địa điểm triển khai" value={event.location} wide/><Metric icon={<CalendarClock size={16}/>} label="Lịch dự kiến" value={event.startsAt.toLocaleString("vi-VN", { dateStyle: "short", timeStyle: "short", timeZone: "Asia/Ho_Chi_Minh" })} wide/></section>
  <section className="overflow-hidden rounded-[2rem] border border-[#d2ad5d] bg-white shadow-lg"><div className="bg-[#fbf2e7] px-5 py-4"><p className="flex items-center gap-2 text-sm font-semibold"><ReceiptText size={17} className="text-[#c64b32]"/> Bill Tâm An Business</p></div><div className="space-y-3 p-5 text-sm"><Row label="Giá trị dịch vụ" value={formatMoney(event.subtotalAmount)}/>{event.discountAmount ? <Row label="Ưu đãi doanh nghiệp" value={`− ${formatMoney(event.discountAmount)}`} green/> : null}<Row label="Phí điều phối & di chuyển" value={formatMoney(event.transportFee)}/><div className="border-t border-dashed border-[#ddcfc6] pt-3"><Row label="Tổng Bill sau ưu đãi" value={formatMoney(event.totalAmount)} strong/></div><Row label="Đã cọc" value={formatMoney(depositConfirmed?.amount ?? Math.min(event.paidAmount, event.depositAmount))} green/><Row label={event.paymentStatus === "PAID" ? "Đã thanh toán đủ" : "Còn lại"} value={event.paymentStatus === "PAID" ? formatMoney(event.totalAmount) : formatMoney(due)} strong={event.paymentStatus !== "PAID"}/>{event.tipPayout ? <Row label="Tip KTV trưởng ngoài Bill" value={formatMoney(event.tipPayout.amount)} green/> : null}</div><div className="grid grid-cols-2 border-t border-[#eee1d8] bg-[#fdf8f3] p-4 text-center"><div><p className="text-[10px] uppercase text-[#826f66]">Cọc</p><p className="mt-1 text-xs font-semibold">{depositConfirmed ? "Đã đối soát" : "Chưa đối soát"}</p></div><div className="border-l border-[#e7d6ca]"><p className="text-[10px] uppercase text-[#826f66]">Phần còn lại</p><p className="mt-1 text-xs font-semibold">{balanceConfirmed || event.paymentStatus === "PAID" ? "Đã đối soát" : "Chưa thanh toán"}</p></div></div></section>
  {event.status === "COMPLETED" ? <BusinessReviewForm eventCode={event.eventCode} initialRating={event.customerRating} initialComment={event.customerComment}/> : <section className="rounded-3xl border border-[#ead6a9] bg-[#fffaf0] p-4 text-xs leading-5 text-[#765b35]"><CircleDollarSign size={18} className="mb-2 text-[#c64b32]"/>Đánh giá sẽ mở sau khi thời gian phục vụ được chốt và ngân hàng xác nhận đủ phần thanh toán còn lại.</section>}
  <Link href="/don-cua-toi" className="block py-2 text-center text-sm font-semibold text-[#c64b32]">Xem tất cả lịch & lịch sử</Link></div></main>;
}

function Metric({ icon, label, value, wide }: { icon: React.ReactNode; label: string; value: string; wide?: boolean }) { return <div className={`${wide ? "col-span-2" : ""} rounded-2xl bg-[#fdf8f3] p-3 text-center`}><span className="mx-auto flex w-fit text-[#c64b32]">{icon}</span><p className="mt-1 text-[9px] uppercase tracking-wide text-[#826f66]">{label}</p><p className="mt-1 text-xs font-semibold leading-5">{value}</p></div>; }
function Row({ label, value, strong, green }: { label: string; value: string; strong?: boolean; green?: boolean }) { return <div className="flex items-center justify-between gap-3"><span className={strong ? "font-semibold" : "text-[#76665d]"}>{label}</span><span className={`${strong ? "text-base font-bold text-[#c64b32]" : "font-semibold"} ${green ? "text-[#9a5a16]" : ""}`}>{value}</span></div>; }
